services:
  sandbox:
    image: registry.coregame.de/core/sandbox:latest
    volumes:
      - ..:/workspace:cached
    stdin_open: true
    networks:
      - sandbox

  visualizer:
    image: registry.coregame.de/core/visualizer:latest
    environment:
      PORT: 80
      SOCKET_SERVER: "sandbox:4242"
      HOST: "127.0.0.1:4040"
    ports:
      - 4040:80
    networks:
      - sandbox

networks:
  sandbox:
