name: "Build my-core-bot devcontainer image"

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  checkout:
    runs-on: self-hosted
    env:
      PATH: "/vscode/vscode-server/bin/linux-x64/e7e037083ff4455cf320e344325dacb480062c3c/bin/remote-cli:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: registry.coregame.de
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./.github/workflows/my-core-bot-Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: registry.coregame.de/core/core-event-0:${{ github.ref_name }}, registry.coregame.de/core/core-event-0:latest
